#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: ./setup_pi_chatbot.sh [--speaker <MAC-or-name>]

Options:
  --speaker  Bluetooth MAC address or advertised name of the speaker you
             want the chatbot to use for audio playback. If omitted the
             system's default audio output will be used.
EOF
}

SPEAKER_IDENTIFIER=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --speaker)
      shift
      [[ $# -gt 0 ]] || { echo "error: --speaker requires an argument" >&2; exit 1; }
      SPEAKER_IDENTIFIER="$1"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "error: unknown option $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "${GITHUB_TOKEN:-}" ]]; then
  echo "error: GITHUB_TOKEN environment variable is not set." >&2
  echo "       Generate a GitHub personal access token with GitHub Models access" >&2
  echo "       and export it before running this script." >&2
  exit 1
fi

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd "$SCRIPT_DIR"

if [[ ! -f "requirements.txt" ]]; then
  echo "error: requirements.txt not found (run from project root)." >&2
  exit 1
fi

echo "📦 Updating Raspberry Pi packages (requires sudo)…"
sudo apt-get update -y
sudo apt-get install -y \
  python3 \
  python3-venv \
  python3-pip \
  bluez \
  bluez-tools \
  pulseaudio \
  pulseaudio-module-bluetooth \
  portaudio19-dev \
  libespeak-ng1 \
  espeak-ng \
  git

if [[ ! -d "venv" ]]; then
  echo "🐍 Creating Python virtual environment…"
  python3 -m venv venv
fi

source venv/bin/activate

python -m pip install --upgrade pip setuptools wheel
python -m pip install -r requirements.txt

env_file=".env"

cat <<EOF > "$env_file"
# Auto-generated by setup_pi_chatbot.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
GITHUB_TOKEN=${GITHUB_TOKEN}
GITHUB_MODELS_ENDPOINT=${GITHUB_MODELS_ENDPOINT:-https://models.github.ai/inference}
GITHUB_MODEL=${GITHUB_MODEL:-openai/gpt-5-chat}
BLUETOOTH_DEVICE_IDENTIFIER=${SPEAKER_IDENTIFIER}
SPEECH_RATE=${SPEECH_RATE:-175}
TEMPERATURE=${TEMPERATURE:-0.7}
MAX_RESPONSE_TOKENS=${MAX_RESPONSE_TOKENS:-600}
CONVERSATION_ID=${CONVERSATION_ID:-pi-console}
LANGUAGE=${LANGUAGE:-en}
DEBUG=${DEBUG:-True}
EOF

chmod 600 "$env_file"

echo "✅ Setup complete. To start the chatbot run:"
echo ""
echo "    source venv/bin/activate"
echo "    python src/pi_voice_chatbot.py"
echo ""
echo "Tip: pair your Bluetooth speaker ahead of time using 'bluetoothctl'."
